### ISSUE TITLE
Invalid example with httpMethod?

### ISSUE THREAD

**Issue by btraut** [htunnicliff/next-api-middleware#65]
**Describe the bug**
It's possible I'm misunderstanding usage, but after reading the executor code, I think the `httpMethod` example in the readme is buggy. It appears that executor expects a middleware to always either call next or to throw something. Without either, `cleanupPromise` is never resolved or rejected, and the line `await cleanupPromise.promise;` is forever pending.

**To Reproduce**
1. Add the `httpMethod` example to your codebase.
2. Make a request to a handler with an invalid HTTP method.
3. `res.status` and `res.end` are called properly, but the middleware never resolves.

**Expected behavior**
If a middleware promise resolves and `next` was never called, it should be assumed that none of the downstream middlewares or handlers should be called, and the teardown stack should be resolved.

As a workaround, I've decided to add a `throw new Error()` after `res.end()` is called in the `httpMethod` example, but this rejects the whole handler+middleware call. This isn't what I want because 404ing an invalid HTTP verb is an example of the handler handling the request properly.

**Comment by htunnicliff** [comment]
Hey @btraut – thanks for catching this. If you have a better working version of the example, I'd gratefully accept a PR.

**Comment by btraut** [comment]
Hey, sorry. Just noticed this question. After running into a few additional challenges with middleware, I decided to switch away from next as an API server. Unfortunately, that means I don't have PR to put up.

Best of luck!
